### ISSUE TITLE
[Feature Request] Publish docker image for MCXboxBroadcast standalone

### ISSUE THREAD

**Issue by RealTriassic** [rtm516/MCXboxBroadcast#59]
I think publishing an official docker image for MCXboxBroadcast that is updated every time a new release is made would be really nice for users that are not running Pterodactyl Panel or simply wish to run it outside of Pterodactyl.

**Comment by Ryuo1** [comment]
+1

**Comment by JoshLoecker** [comment]
I'm not sure how to integrate a docker build process into this project but I have a very simple `Dockerfile` and `docker-compose.yaml` that can be used

```Dockerfile
FROM eclipse-temurin:21 as builder
RUN curl -L -o /MCXboxBroadcastStandalone.jar https://github.com/rtm516/MCXboxBroadcast/releases/latest/download/MCXboxBroadcastStandalone.jar

FROM eclipse-temurin:21
COPY --from=builder /MCXboxBroadcastStandalone.jar /

WORKDIR /app
CMD [ "java", "-jar", "/MCXboxBroadcastStandalone.jar" ]
```

```yaml
services:
  mcxboxbroadcast:
    container_name: mcxboxbroadcast
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - <HOST MACHINE DIRECTORY>:/app
```

1. Create a file named `Dockerfile` and paste the contents of the first code block into that file
2. Create a second file named `docker-compose.yml` and paste the contents of the second code block into that file
3. Run `docker compose up -d` to build and start the project
4. Edit required settings under the mapped directory
5. Restart using `docker compose restart` to apply changes
